### ISSUE TITLE
Cheats are turned on is there a way to turn them off

### ISSUE THREAD

**Issue by aihooo444** [ArcadeTV/msu-md_castleOfIllusion#4]
Still has cheat enabled after 1.1 patch at least on the us version I have not tried jp version yet.

What happens is after first hit it goes up to full health and you cant get it to drop anymore.

**Comment by ArcadeTV** [comment]
I just double-checked by re-creating the bps and launched the patched v1.1 game. Also the checksums match...
Do you maybe have auto-load for savegames turned on? What Platform do you play on?

**Comment by ArcadeTV** [comment]
I re-uploadedthe release-zipfile again, just in case:
https://github.com/ArcadeTV/msu-md_castleOfIllusion/releases/tag/v1.1

**Comment by aihooo444** [comment]
Playing on Mister and now I have re-patched it and it works great thanks.
